name: data_models

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_serializable: ^6.6.2
  firebase_admin_interop:
    git:
      url: https://github.com/berkmancenter/firebase-admin-interop.git
  enum_to_string: ^2.0.1
  namefully: ^0.2.1
  uuid: ^4.1.0
  collection: ^1.19.0
  http_parser: ^4.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.3
  freezed: ^2.4.1

dependency_overrides:
  watcher: ^1.1.0
